<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="2" failures="2">
  <testsuite name="Root Suite" timestamp="2019-09-04T09:41:40" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="Todo app" timestamp="2019-09-04T09:41:40" tests="2" failures="2" time="0">
    <testcase name="Todo app Navigating to the todo app" time="0" classname="Navigating to the todo app">
      <failure message="Timed out retrying: Expected to find element: &apos;[data-title-e2e-test]&apos;, but never found it." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find element: '[data-title-e2e-test]', but never found it.
    at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:85348:11)
    at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:85303:18)
    at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:85335:17)
    at retry (http://localhost:3000/__cypress/runner/cypress_runner.js:77321:16)
    at onFailFn (http://localhost:3000/__cypress/runner/cypress_runner.js:68422:16)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:118962:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:116898:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:116955:18)
    at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:117000:10)
    at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:117075:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:113687:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:113697:10)
    at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:113571:14)
    at <anonymous>]]></failure>
    </testcase>
    <testcase name="Todo app Creating and deleting items" time="0" classname="Creating and deleting items">
      <failure message="Timed out retrying: Expected to find element: &apos;[data-new-item-text-field-e2e-test]&apos;, but never found it." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find element: '[data-new-item-text-field-e2e-test]', but never found it.
    at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:85348:11)
    at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:85303:18)
    at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:85335:17)
    at retry (http://localhost:3000/__cypress/runner/cypress_runner.js:77321:16)
    at onFailFn (http://localhost:3000/__cypress/runner/cypress_runner.js:68422:16)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:118962:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:116898:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:116955:18)
    at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:117000:10)
    at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:117075:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:113687:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:113697:10)
    at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:113571:14)
    at <anonymous>]]></failure>
    </testcase>
  </testsuite>
</testsuites>